apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: web
spec:
  containers:
    - image: 'fidelina/nginx:v1'
      imagePullPolicy: IfNotPresent
      name: web
      ports:
        - containerPort: 8000
          name: web
          protocol: TCP
      resources:
        limits:
          cpu: '1'
          memory: 1Mi
        requests:
          cpu: 2m
          memory: 5Mi
      volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
    - image: busybox:1.31.0
      name: init-pages 
      command: ["sh", "-c", "wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh"]
      volumeMounts:
      - name: app
        mountPath: /app
  volumes:
    - name: app
      emptyDir: {}


